"""Добавление поля contacts в User

Revision ID: ba2a17fa7953
Revises: a69a9e4efd7d
Create Date: 2025-12-15 13:24:21.251289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2a17fa7953'
down_revision: Union[str, None] = 'a69a9e4efd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contacts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contacts')
    # ### end Alembic commands ###
