// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int64
	Login        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type GroupGenre struct {
	ID      int32
	GroupID int64
	Name    string
}

type GroupInvitation struct {
	ID        int32
	GroupID   int64
	UserID    int64
	Role      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type GroupLikesUser struct {
	ID            int32
	SwiperGroupID int64
	TargetUserID  int64
	Action        string
	CreatedAt     pgtype.Timestamptz
}

type GroupMember struct {
	ID      int32
	GroupID int64
	UserID  int64
	Role    string
	IsAdmin bool
}

type GroupProfile struct {
	ID               int64
	Name             string
	City             pgtype.Text
	FormationDate    pgtype.Int4
	Platforms        []string
	Description      pgtype.Text
	IsVisible        bool
	SeriousnessLevel pgtype.Text
	FinancialStatus  pgtype.Text
	Concerts         []byte
	CreatedAt        pgtype.Timestamptz
}

type Instrument struct {
	ID               int32
	UserID           int64
	Name             string
	ProficiencyLevel int32
}

type User struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 bool
	PhotoPath                 pgtype.Text
	AudioPath                 pgtype.Text
}

type UserGenre struct {
	ID     int32
	UserID int64
	Name   string
}

type UserLikesGroup struct {
	ID            int32
	SwiperUserID  int64
	TargetGroupID int64
	Action        string
	CreatedAt     pgtype.Timestamptz
}

type UserLikesUser struct {
	ID           int32
	SwiperUserID int64
	TargetUserID int64
	Action       string
	CreatedAt    pgtype.Timestamptz
}
