// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserGenre = `-- name: AddUserGenre :exec

INSERT INTO user_genres (user_id, name) 
VALUES ($1, $2)
`

type AddUserGenreParams struct {
	UserID int64
	Name   string
}

// --- GENRES ---
func (q *Queries) AddUserGenre(ctx context.Context, arg AddUserGenreParams) error {
	_, err := q.db.Exec(ctx, addUserGenre, arg.UserID, arg.Name)
	return err
}

const addUserInstrument = `-- name: AddUserInstrument :exec

INSERT INTO instruments (user_id, name, proficiency_level) 
VALUES ($1, $2, $3)
`

type AddUserInstrumentParams struct {
	UserID           int64
	Name             string
	ProficiencyLevel int32
}

// --- INSTRUMENTS ---
func (q *Queries) AddUserInstrument(ctx context.Context, arg AddUserInstrumentParams) error {
	_, err := q.db.Exec(ctx, addUserInstrument, arg.UserID, arg.Name, arg.ProficiencyLevel)
	return err
}

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE login = $1)
`

func (q *Queries) CheckAccountExists(ctx context.Context, login string) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountExists, login)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one


INSERT INTO accounts (login, password_hash)
VALUES ($1, $2)
RETURNING id
`

type CreateAccountParams struct {
	Login        string
	PasswordHash string
}

// queries.sql
// --- AUTH QUERIES ---
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Login, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserProfile = `-- name: CreateUserProfile :exec
INSERT INTO users (id, name, city, age, contacts, theoretical_knowledge_level, has_performance_experience, about_me, external_link, is_visible)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserProfileParams struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 bool
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Age,
		arg.Contacts,
		arg.TheoreticalKnowledgeLevel,
		arg.HasPerformanceExperience,
		arg.AboutMe,
		arg.ExternalLink,
		arg.IsVisible,
	)
	return err
}

const deleteUserGenres = `-- name: DeleteUserGenres :exec
DELETE FROM user_genres WHERE user_id = $1
`

func (q *Queries) DeleteUserGenres(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserGenres, userID)
	return err
}

const deleteUserInstruments = `-- name: DeleteUserInstruments :exec
DELETE FROM instruments WHERE user_id = $1
`

func (q *Queries) DeleteUserInstruments(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserInstruments, userID)
	return err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, login, password_hash 
FROM accounts 
WHERE login = $1 LIMIT 1
`

type GetAccountByLoginRow struct {
	ID           int64
	Login        string
	PasswordHash string
}

func (q *Queries) GetAccountByLogin(ctx context.Context, login string) (GetAccountByLoginRow, error) {
	row := q.db.QueryRow(ctx, getAccountByLogin, login)
	var i GetAccountByLoginRow
	err := row.Scan(&i.ID, &i.Login, &i.PasswordHash)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, name, city, age, contacts, theoretical_knowledge_level, has_performance_experience, about_me, external_link, is_visible, photo_path, audio_path 
FROM public.users
WHERE id = $1 LIMIT 1
`

// --- USER PROFILE QUERIES ---
// Получение одного профиля по ID
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Age,
		&i.Contacts,
		&i.TheoreticalKnowledgeLevel,
		&i.HasPerformanceExperience,
		&i.AboutMe,
		&i.ExternalLink,
		&i.IsVisible,
		&i.PhotoPath,
		&i.AudioPath,
	)
	return i, err
}

const getUserGenres = `-- name: GetUserGenres :many
SELECT name 
FROM public.user_genres 
WHERE user_id = $1
`

// Получаем все жанры пользователя одним списком строк
func (q *Queries) GetUserGenres(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserGenres, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInstruments = `-- name: GetUserInstruments :many
SELECT name, proficiency_level 
FROM public.instruments 
WHERE user_id = $1
`

type GetUserInstrumentsRow struct {
	Name             string
	ProficiencyLevel int32
}

// Получаем инструменты и уровни владения
func (q *Queries) GetUserInstruments(ctx context.Context, userID int64) ([]GetUserInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, getUserInstruments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInstrumentsRow
	for rows.Next() {
		var i GetUserInstrumentsRow
		if err := rows.Scan(&i.Name, &i.ProficiencyLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET 
    name = COALESCE($2, name),
    city = COALESCE($3, city),
    age = COALESCE($4, age),
    contacts = COALESCE($5, contacts),
    theoretical_knowledge_level = COALESCE($6, theoretical_knowledge_level),
    has_performance_experience = COALESCE($7, has_performance_experience),
    about_me = COALESCE($8, about_me),
    external_link = COALESCE($9, external_link),
    is_visible = COALESCE($10, is_visible)
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 pgtype.Bool
}

// Получаем обновленный профиль у юзера
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Age,
		arg.Contacts,
		arg.TheoreticalKnowledgeLevel,
		arg.HasPerformanceExperience,
		arg.AboutMe,
		arg.ExternalLink,
		arg.IsVisible,
	)
	return err
}
