// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInteraction = `-- name: AddInteraction :exec
INSERT INTO user_likes_user (swiper_user_id, target_user_id, action)
VALUES ($1, $2, $3)
ON CONFLICT (swiper_user_id, target_user_id) 
DO UPDATE SET action = EXCLUDED.action, created_at = NOW()
`

type AddInteractionParams struct {
	SwiperUserID int64
	TargetUserID int64
	Action       pgtype.Text
}

// Добавляем лайк или дизлайк. Используем ON CONFLICT, чтобы избежать ошибок при повторном свайпе
func (q *Queries) AddInteraction(ctx context.Context, arg AddInteractionParams) error {
	_, err := q.db.Exec(ctx, addInteraction, arg.SwiperUserID, arg.TargetUserID, arg.Action)
	return err
}

const addUserGenre = `-- name: AddUserGenre :exec

INSERT INTO user_genres (user_id, name) 
VALUES ($1, $2)
`

type AddUserGenreParams struct {
	UserID int64
	Name   string
}

// --- GENRES ---
func (q *Queries) AddUserGenre(ctx context.Context, arg AddUserGenreParams) error {
	_, err := q.db.Exec(ctx, addUserGenre, arg.UserID, arg.Name)
	return err
}

const addUserInstrument = `-- name: AddUserInstrument :exec

INSERT INTO instruments (user_id, name, proficiency_level) 
VALUES ($1, $2, $3)
`

type AddUserInstrumentParams struct {
	UserID           int64
	Name             string
	ProficiencyLevel int32
}

// --- INSTRUMENTS ---
func (q *Queries) AddUserInstrument(ctx context.Context, arg AddUserInstrumentParams) error {
	_, err := q.db.Exec(ctx, addUserInstrument, arg.UserID, arg.Name, arg.ProficiencyLevel)
	return err
}

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE login = $1)
`

func (q *Queries) CheckAccountExists(ctx context.Context, login string) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountExists, login)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkMatch = `-- name: CheckMatch :one
SELECT EXISTS (
    SELECT 1 FROM user_likes_user 
    WHERE swiper_user_id = $1 AND target_user_id = $2 AND action = 'like'
)
`

type CheckMatchParams struct {
	SwiperUserID int64
	TargetUserID int64
}

// Проверяем, лайкал ли нас этот пользователь в ответ
func (q *Queries) CheckMatch(ctx context.Context, arg CheckMatchParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMatch, arg.SwiperUserID, arg.TargetUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProfileExists = `-- name: CheckProfileExists :one
SELECT EXISTS(SELECT 1 FROM public.users WHERE id = $1)
`

func (q *Queries) CheckProfileExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkProfileExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one


INSERT INTO accounts (login, password_hash)
VALUES ($1, $2)
RETURNING id
`

type CreateAccountParams struct {
	Login        string
	PasswordHash string
}

// queries.sql
// --- AUTH QUERIES ---
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Login, arg.PasswordHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserProfile = `-- name: CreateUserProfile :exec
INSERT INTO users (id, name, city, age, contacts, theoretical_knowledge_level, has_performance_experience, about_me, external_link, is_visible)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserProfileParams struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 bool
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Age,
		arg.Contacts,
		arg.TheoreticalKnowledgeLevel,
		arg.HasPerformanceExperience,
		arg.AboutMe,
		arg.ExternalLink,
		arg.IsVisible,
	)
	return err
}

const deleteUserGenres = `-- name: DeleteUserGenres :exec
DELETE FROM user_genres WHERE user_id = $1
`

func (q *Queries) DeleteUserGenres(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserGenres, userID)
	return err
}

const deleteUserInstruments = `-- name: DeleteUserInstruments :exec
DELETE FROM instruments WHERE user_id = $1
`

func (q *Queries) DeleteUserInstruments(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserInstruments, userID)
	return err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, login, password_hash 
FROM accounts 
WHERE login = $1 LIMIT 1
`

type GetAccountByLoginRow struct {
	ID           int64
	Login        string
	PasswordHash string
}

func (q *Queries) GetAccountByLogin(ctx context.Context, login string) (GetAccountByLoginRow, error) {
	row := q.db.QueryRow(ctx, getAccountByLogin, login)
	var i GetAccountByLoginRow
	err := row.Scan(&i.ID, &i.Login, &i.PasswordHash)
	return i, err
}

const getFeedProfiles = `-- name: GetFeedProfiles :many
SELECT 
    u.id, u.name, u.city, u.age, u.contacts, u.theoretical_knowledge_level, 
    u.has_performance_experience, u.about_me, u.external_link, u.is_visible,
    u.photo_path, u.audio_path,
    COALESCE(
        (SELECT array_agg(ug.name)::text[] FROM user_genres ug WHERE ug.user_id = u.id), 
        '{}'::text[]
    ) as genres,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object('name', i.name, 'proficiency_level', i.proficiency_level)) 
         FROM instruments i WHERE i.user_id = u.id), 
        '[]'::jsonb
    ) as instruments
FROM public.users u
WHERE u.id != $1 
  AND u.is_visible = true
  AND (cardinality($3::text[]) = 0 OR u.city = ANY($3::text[]))
  AND (cardinality($4::text[]) = 0 OR EXISTS (
      SELECT 1 FROM user_genres ug WHERE ug.user_id = u.id AND ug.name = ANY($4::text[])
  ))
  AND (cardinality($5::text[]) = 0 OR EXISTS (
      SELECT 1 FROM instruments i WHERE i.user_id = u.id 
      AND i.name = ANY($5::text[])
      AND ($6::int IS NULL OR i.proficiency_level >= $6)
  ))
  AND ($7::text IS NULL OR u.has_performance_experience = $7::text)
  AND ($8::int IS NULL OR u.theoretical_knowledge_level >= $8)
  AND NOT EXISTS (
      SELECT 1 FROM user_likes_user ul WHERE ul.swiper_user_id = $1 AND ul.target_user_id = u.id
  )
ORDER BY RANDOM()
LIMIT $2
`

type GetFeedProfilesParams struct {
	ID             int64
	Limit          int32
	Cities         []string
	Genres         []string
	Instruments    []string
	MinProficiency pgtype.Int4
	HasExp         pgtype.Text
	TheoryLevel    pgtype.Int4
}

type GetFeedProfilesRow struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 bool
	PhotoPath                 pgtype.Text
	AudioPath                 pgtype.Text
	Genres                    interface{}
	Instruments               interface{}
}

func (q *Queries) GetFeedProfiles(ctx context.Context, arg GetFeedProfilesParams) ([]GetFeedProfilesRow, error) {
	rows, err := q.db.Query(ctx, getFeedProfiles,
		arg.ID,
		arg.Limit,
		arg.Cities,
		arg.Genres,
		arg.Instruments,
		arg.MinProficiency,
		arg.HasExp,
		arg.TheoryLevel,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedProfilesRow
	for rows.Next() {
		var i GetFeedProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Age,
			&i.Contacts,
			&i.TheoreticalKnowledgeLevel,
			&i.HasPerformanceExperience,
			&i.AboutMe,
			&i.ExternalLink,
			&i.IsVisible,
			&i.PhotoPath,
			&i.AudioPath,
			&i.Genres,
			&i.Instruments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicFeed = `-- name: GetPublicFeed :many
SELECT 
    u.id, u.name, u.city, u.age, u.contacts, u.theoretical_knowledge_level, 
    u.has_performance_experience, u.about_me, u.external_link, u.is_visible,
    u.photo_path, u.audio_path,
    COALESCE(
        (SELECT array_agg(ug.name)::text[] FROM user_genres ug WHERE ug.user_id = u.id), 
        '{}'::text[]
    ) as genres,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'name', i.name, 
            'proficiency_level', i.proficiency_level
        )) FROM instruments i WHERE i.user_id = u.id), 
        '[]'::jsonb
    ) as instruments
FROM public.users u
WHERE u.is_visible = true
ORDER BY RANDOM()
LIMIT $1
`

type GetPublicFeedRow struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 bool
	PhotoPath                 pgtype.Text
	AudioPath                 pgtype.Text
	Genres                    interface{}
	Instruments               interface{}
}

// Получение профилей для неавторизованных пользователей
func (q *Queries) GetPublicFeed(ctx context.Context, limit int32) ([]GetPublicFeedRow, error) {
	rows, err := q.db.Query(ctx, getPublicFeed, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicFeedRow
	for rows.Next() {
		var i GetPublicFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Age,
			&i.Contacts,
			&i.TheoreticalKnowledgeLevel,
			&i.HasPerformanceExperience,
			&i.AboutMe,
			&i.ExternalLink,
			&i.IsVisible,
			&i.PhotoPath,
			&i.AudioPath,
			&i.Genres,
			&i.Instruments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one

SELECT id, name, city, age, contacts, theoretical_knowledge_level, has_performance_experience, about_me, external_link, is_visible, photo_path, audio_path 
FROM public.users
WHERE id = $1 LIMIT 1
`

// --- USER PROFILE QUERIES ---
// Получение одного профиля по ID
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Age,
		&i.Contacts,
		&i.TheoreticalKnowledgeLevel,
		&i.HasPerformanceExperience,
		&i.AboutMe,
		&i.ExternalLink,
		&i.IsVisible,
		&i.PhotoPath,
		&i.AudioPath,
	)
	return i, err
}

const getUserGenres = `-- name: GetUserGenres :many
SELECT name 
FROM public.user_genres 
WHERE user_id = $1
`

// Получаем все жанры пользователя одним списком строк
func (q *Queries) GetUserGenres(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserGenres, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInstruments = `-- name: GetUserInstruments :many
SELECT name, proficiency_level 
FROM public.instruments 
WHERE user_id = $1
`

type GetUserInstrumentsRow struct {
	Name             string
	ProficiencyLevel int32
}

// Получаем инструменты и уровни владения
func (q *Queries) GetUserInstruments(ctx context.Context, userID int64) ([]GetUserInstrumentsRow, error) {
	rows, err := q.db.Query(ctx, getUserInstruments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserInstrumentsRow
	for rows.Next() {
		var i GetUserInstrumentsRow
		if err := rows.Scan(&i.Name, &i.ProficiencyLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET 
    name = COALESCE($2, name),
    city = COALESCE($3, city),
    age = COALESCE($4, age),
    contacts = COALESCE($5, contacts),
    theoretical_knowledge_level = COALESCE($6, theoretical_knowledge_level),
    has_performance_experience = COALESCE($7, has_performance_experience),
    about_me = COALESCE($8, about_me),
    external_link = COALESCE($9, external_link),
    is_visible = COALESCE($10, is_visible),
    photo_path = COALESCE($11, photo_path),
    audio_path = COALESCE($12, audio_path)
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID                        int64
	Name                      pgtype.Text
	City                      pgtype.Text
	Age                       pgtype.Int4
	Contacts                  pgtype.Text
	TheoreticalKnowledgeLevel pgtype.Int4
	HasPerformanceExperience  pgtype.Text
	AboutMe                   pgtype.Text
	ExternalLink              pgtype.Text
	IsVisible                 pgtype.Bool
	PhotoPath                 pgtype.Text
	AudioPath                 pgtype.Text
}

// Получаем обновленный профиль у юзера
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Age,
		arg.Contacts,
		arg.TheoreticalKnowledgeLevel,
		arg.HasPerformanceExperience,
		arg.AboutMe,
		arg.ExternalLink,
		arg.IsVisible,
		arg.PhotoPath,
		arg.AudioPath,
	)
	return err
}
